"use client";
import { useState } from "react";
import { ArrowUpRight, TrendingDown, TrendingUp } from "lucide-react";
import { useDashboard } from "@/app/providers";
import { AssetChart, IncomeBars } from "./charts";
import { AccountList, TransactionList } from "./lists";
import { Button } from "@/components/ui/button";
export function MobileDashboard(){const {view}=useDashboard();return <main className="pb-24 lg:hidden"><div className="px-5 pt-5"><h2 className="text-[29px] font-bold tracking-tight">{view==='wallet'?'$120,420.50':'€114.158,63'}</h2><p className="mt-1 text-xs text-muted">Total balance from all accounts <b className="ml-1 text-blue">{view==='wallet'?'USD':'EUR'}</b></p></div>{view==='overview'?<Overview/>:view==='analytics'?<Analytics/>:<Wallet/>}</main>}
function Overview(){const [tab,setTab]=useState<'total'|'avg'>('total');return <div className="px-5"><div className="mt-6 flex rounded-xl border border-line bg-white p-1"><button onClick={()=>setTab('total')} className={`h-8 flex-1 rounded-lg text-[11px] font-bold ${tab==='total'?'bg-black text-white':''}`}>Total income</button><button onClick={()=>setTab('avg')} className={`h-8 flex-1 rounded-lg text-[11px] font-bold ${tab==='avg'?'bg-black text-white':''}`}>Avg. income</button></div><div className="mt-5"><p className="text-lg font-bold">{tab==='total'?'€10.840,00':'€1.850,40'}</p><p className="text-xs text-muted">{tab==='total'?'Total income':'Avg. income'}</p><div className="mt-4">{tab==='total'?<AssetChart compact={false}/>:<IncomeBars/>}</div></div><div className="mt-6 border-t border-line pt-6"><p className="mb-3 text-xs text-muted">Your cards</p><AccountList mobile/></div></div>}
function Analytics(){return <><div className="mt-8"><AssetChart dual compact/></div><div className="-mt-1 px-5"><Metric title="Income" amount="€9.650,00" rate="+5.7%" green/><Metric title="Expenses" amount="€7.845,00" rate="+16.4%"/><p className="mb-3 mt-7 text-xs text-muted">Latest transactions</p><div className="rounded-lg bg-white px-4"><TransactionList short/></div></div></>}
function Metric({title,amount,rate,green=false}:{title:string;amount:string;rate:string;green?:boolean}){return <div className="mb-2 flex items-end justify-between rounded-lg bg-white px-5 py-4"><div><p className="text-xs text-muted">{title}</p><p className="mt-2 text-lg font-bold">{amount}</p></div><div className="text-right">{green?<TrendingUp size={14} className="ml-auto text-green-500"/>:<TrendingDown size={14} className="ml-auto text-pink-500"/>}<p className="mt-3 text-[10px] font-bold">{rate}</p></div></div>}
function Wallet(){return <><div className="mt-6 flex gap-3 overflow-hidden px-5"><Summary title="Income" amount="$9.650,00" sub="84 Transactions" rate="+10%"/><Summary title="Spendings" amount="$7.845,00" sub="58 Transactions" rate="-2%"/></div><div className="mt-3"><AssetChart compact/></div><div className="px-5"><p className="mb-3 text-xs text-muted">Payment accounts</p><AccountList mobile/><Button className="mt-3 h-11 w-full bg-transparent text-xs">◴&nbsp;&nbsp; See detailed report</Button></div></>}
function Summary({title,amount,sub,rate}:{title:string;amount:string;sub:string;rate:string}){return <div className="min-w-[200px] rounded-xl bg-white p-5"><div className="flex justify-between"><span className="text-xs text-muted">{title}</span><ArrowUpRight size={14} className={rate.startsWith('+')?'text-green-500':'text-pink-500'}/></div><p className="mt-3 text-xl font-bold">{amount}</p><div className="mt-1 flex justify-between text-[10px] font-bold"><span>{sub}</span><span className={rate.startsWith('+')?'text-green-500':'text-pink-500'}>{rate}</span></div></div>}
