"use client";

import { useState } from "react";
import { ArrowLeft, Bell, ChevronRight, Laptop, LockKeyhole, Search, ShieldCheck, Smartphone, UserRound, UsersRound } from "lucide-react";
import { Sidebar } from "@/components/dashboard/sidebar";
import { MobileNav } from "@/components/dashboard/mobile-nav";

type Tab = "Profile" | "Security" | "Social Networks" | "APIs" | "Notifications" | "Payment Limits";
const tabs: Tab[] = ["Profile", "Security", "Social Networks", "APIs", "Notifications", "Payment Limits"];

const Field = ({ label, value }: { label: string; value: string }) => <div className="border-b border-[#dbe2e2] py-4 last:border-0"><p className="text-[11px] text-muted">{label}</p><p className="mt-1 text-sm font-bold">{value}</p></div>;
const Panel = ({ children, className = "" }: { children: React.ReactNode; className?: string }) => <div className={`rounded-2xl bg-[#f1f5f4] px-5 py-1 md:px-6 ${className}`}>{children}</div>;
const Toggle = ({ on = false }: { on?: boolean }) => <span className={`relative h-5 w-9 rounded-full border ${on ? "border-blue bg-blue" : "border-line bg-white"}`}><span className={`absolute top-0.5 h-3.5 w-3.5 rounded-full ${on ? "right-0.5 bg-white" : "left-0.5 bg-ink"}`}/></span>;

function Profile() { return <><h2 className="section-title">Account information</h2><Panel><Field label="Full name" value="Sebastian Bennett"/><Field label="Gender" value="Female"/><Field label="Date of birth" value="January 24, 1983"/></Panel><h2 className="section-title">Contact details</h2><Panel><Field label="Email address" value="seb.bennett@gmail.com"/><Field label="Phone number" value="+995 590 558 124"/><Field label="Address" value="83222 Dicki View, South Pasqualeview, RI 79216-3100"/></Panel></> }

function Security() { return <><h2 className="section-title">Login details</h2><Panel><Field label="Current password" value="••••••"/><Field label="Security questions" value="Your fathers name"/><Field label="2-Step verification" value="Enabled"/></Panel><h2 className="section-title">Security credentials</h2><Panel>{[[Laptop,"01 Apr 2021 at 06:25PM","Mac OS Safari 15.1"],[Laptop,"20 Oct 2021 at 04:32AM","Windows 11 Mozilla Firefox"],[Smartphone,"19 Oct 2021 at 06:30AM","iOS Safari 15.1"]].map(([Icon,date,name],i)=><div key={String(name)} className="flex items-center gap-4 border-b border-[#dbe2e2] py-4 last:border-0"><span className="flex h-10 w-10 items-center justify-center rounded-lg border border-line bg-white"><Icon size={16}/></span><div className="flex-1"><p className="text-[11px] text-muted">{String(date)}</p><p className="mt-1 text-sm font-bold">{String(name)}</p></div>{i===0&&<span className="hidden rounded-lg bg-black px-4 py-2 text-[10px] font-bold text-white md:block">Current session</span>}</div>)}</Panel></> }

const notices = [["Product updates","Receive messages from our platform",true],["Reminders","Receive booking reminders, pricing notices",false],["Promotions and tips","Receive coupons, promotions, surveys",true],["Policy and community","Receive updates on job regulations",true],["Account support","Receive messages about your account, your trips, legal alerts",false],["Reminders","Upcoming payments and balance changes",false],["Policy and community","Receive updates on government regulations",true]] as const;
function Notifications() { return <><h2 className="section-title md:hidden">Setup preferred notifications</h2><h2 className="section-title hidden md:block">Notifications</h2><Panel>{notices.map(([label,text,on])=><div key={text} className="flex items-center gap-3 border-b border-[#dbe2e2] py-4 last:border-0"><div className="flex-1"><p className="text-[11px] text-muted">{label}</p><p className={`mt-1 text-sm font-bold ${!on ? "text-[#747b80]" : ""}`}>{text}</p></div><Toggle on={on}/></div>)}</Panel></> }

const limits = [["Cash withdrawals","8.950 USD","15.000 USD",70],["Private transactions","4.650 USD","5.000 USD",42],["Online payments","850 USD","3.000 USD",22],["One-time purchase in store","Amount limit","1.000 USD",20],["One-time purchase online","Amount limit","2.000 USD",42],["One-time p2p transfer","Amount limit","8.000 USD",75]] as const;
function Limits() { return <><h2 className="section-title md:hidden">Setup limits</h2><h2 className="section-title hidden md:block">Payment Limits</h2><Panel>{limits.map(([label,spent,total,percent],i)=><div key={label} className={`border-b border-[#dbe2e2] py-4 last:border-0 md:grid md:grid-cols-[1fr_145px] md:items-center md:gap-8 ${i>2?"md:hidden":""}`}><div><p className="text-[11px] text-muted">{label}</p><div className="mt-1 flex justify-between gap-2 text-sm"><b>{spent}</b><b className="text-blue">{total}</b></div></div><div className={`relative mt-8 h-1 rounded bg-blue md:mt-0`}><span className="absolute -top-1.5 h-4 w-4 rounded-full bg-white shadow" style={{left:`calc(${percent}% - 8px)`}}/></div></div>)}</Panel></> }

function MobileHome({ select }: { select: (tab: Tab) => void }) { return <div className="md:hidden"><label className="flex h-13 items-center gap-3 rounded-xl border border-line bg-white px-4 shadow"><Search size={18} className="text-muted"/><input placeholder="Type to search" className="h-12 w-full outline-none"/></label><div className="my-7 text-center"><div className="mx-auto h-24 w-24 rounded-full bg-gradient-to-br from-slate-800 via-stone-400 to-stone-100"/><h2 className="mt-3 text-2xl font-bold">Sebastian Bennett</h2><p className="text-sm text-muted">seb.bennett@gmail.com</p></div><h2 className="text-xl font-bold">Account</h2><p className="mb-5 mt-1 text-muted">Update your info to keep your account</p><Panel className="py-2">{[[UserRound,"Account information","Profile"],[UsersRound,"Friends","Social Networks"],[Bell,"Notifications","Notifications"],[LockKeyhole,"Security","Security"],[ShieldCheck,"Team members and business","APIs"]].map(([Icon,label,tab])=><button key={String(label)} onClick={()=>select(tab as Tab)} className="flex w-full items-center gap-4 py-3.5 text-left"><Icon size={20}/><b className="flex-1 text-sm">{String(label)}</b><ChevronRight size={15}/></button>)}</Panel></div> }

export function SettingsPage() {
  const [tab,setTab] = useState<Tab | null>(null);
  const active = tab ?? "Profile";
  return <div className="min-h-screen bg-white lg:pl-[210px]"><Sidebar/><header className="hidden h-[76px] items-center justify-between px-14 md:flex"><h1 className="text-base font-bold">Profile settings</h1><div className="flex items-center gap-3"><label className="flex h-10 w-64 items-center gap-3 rounded-lg border border-line px-3"><Search size={16}/><input className="w-full text-xs outline-none" placeholder="Type to search ..."/></label><button className="flex h-10 w-10 items-center justify-center rounded-lg border border-line"><Bell size={16}/></button><div className="h-9 w-9 rounded-full bg-gradient-to-br from-slate-800 via-stone-400 to-stone-100"/></div></header><header className="flex h-[72px] items-center border-b border-line px-6 md:hidden"><button onClick={()=>setTab(null)}><ArrowLeft size={22}/></button><h1 className="flex-1 text-center text-xl font-bold">{tab ?? "Settings"}</h1><div className={`h-8 w-8 rounded-full bg-gradient-to-br from-slate-800 via-stone-400 to-stone-100 ${tab?"":"invisible"}`}/></header>
    <main className="mx-auto max-w-[900px] px-6 pb-32 pt-5 md:px-8 md:pb-8 md:pt-4"><MobileHome select={setTab}/><div className={`${tab ? "block" : "hidden"} md:block`}><div className="mb-7 hidden gap-2 md:flex">{tabs.map(t=><button key={t} onClick={()=>setTab(t)} className={`rounded-lg px-5 py-2.5 text-xs font-bold ${active===t?"bg-black text-white":""}`}>{t}</button>)}</div>{active==="Profile"&&<Profile/>}{active==="Security"&&<Security/>}{active==="Notifications"&&<Notifications/>}{active==="Payment Limits"&&<Limits/>}{(active==="Social Networks"||active==="APIs")&&<><h2 className="section-title">{active}</h2><Panel className="py-8 text-center text-sm text-muted">No settings available yet.</Panel></>}<div className="mt-7 flex justify-between gap-4"><button className="h-12 w-full rounded-lg bg-blue px-6 text-sm font-bold text-white md:w-auto">Update Settings</button><button className="hidden h-12 w-36 rounded-lg bg-[#cbdcff] text-sm font-bold text-blue md:block">Cancel</button></div></div></main><MobileNav/></div>;
}
