"use client";
import { useMemo, useState } from "react";
import { CheckCircle2, ChevronDown } from "lucide-react";
import { Sidebar } from "@/components/dashboard/sidebar";
import { MobileNav } from "@/components/dashboard/mobile-nav";
import { AccountsHeader } from "@/components/accounts/accounts-header";
import { CountryFlag } from "@/components/ui/country-flag";

export function SendMoney(){const [local,setLocal]=useState(false);const [amount,setAmount]=useState('1290.00');const [done,setDone]=useState(false);const conversion=local?0:9.5,fee=5.5;const received=useMemo(()=>Math.max(Number(amount||0)-conversion-fee,0),[amount,conversion]);if(done)return <div className="min-h-screen bg-[#f4f7f7] lg:pl-[210px]"><Sidebar/><AccountsHeader title="Transfer complete"/><main className="flex min-h-[calc(100vh-72px)] flex-col items-center justify-center px-5 text-center"><CheckCircle2 size={72} className="text-green-500"/><h2 className="mt-6 text-3xl font-bold">Money sent</h2><p className="mt-2 text-muted">{received.toFixed(2)} USD was sent to Rustem Tolstobrov.</p><button onClick={()=>setDone(false)} className="mt-7 rounded-lg bg-blue px-8 py-3 font-bold text-white">Make another transfer</button></main><MobileNav/></div>;return <div className="min-h-screen bg-[#f4f7f7] lg:pl-[210px] lg:bg-white"><Sidebar/><AccountsHeader title="Send Money" back="/payments"/><main className="mx-auto max-w-[520px] px-5 pb-24 pt-8"><div className="flex rounded-xl border border-line bg-white p-1"><button onClick={()=>setLocal(false)} className={`h-10 flex-1 rounded-lg text-xs font-bold ${!local?'bg-black text-white':''}`}>International transfer</button><button onClick={()=>setLocal(true)} className={`h-10 flex-1 rounded-lg text-xs font-bold ${local?'bg-black text-white':''}`}>Local transfer</button></div><div className="mt-7 space-y-4"><Select label="Select recipient" value="Rustem Tolstobrov"/><Select label="Select payment account" value="Debit Card **** 7890"/><label className="block text-xs font-bold">You will send<div className="mt-2 flex h-14 items-center rounded-lg border border-line bg-white px-4"><input value={amount} onChange={e=>setAmount(e.target.value.replace(/[^0-9.]/g,''))} className="w-full outline-none"/><span className="mr-2">USD</span><CountryFlag code="US" className="h-5 w-5"/></div></label><div className="space-y-3 px-5 text-xs text-muted">{!local&&<p className="flex justify-between"><span>● &nbsp; Conversion fee</span><b className="text-ink">{conversion.toFixed(2)} USD</b></p>}<p className="flex justify-between"><span>● &nbsp; Transfer fee</span><b className="text-ink">{fee.toFixed(2)} USD</b></p></div><label className="block text-xs font-bold">Recipient will get<div className="mt-2 flex h-14 items-center rounded-lg border border-line bg-white px-4 text-sm">{received.toFixed(2)}</div></label><p className="text-xs leading-5 text-muted">Transfers made on weekends or holidays may take longer. All transfers are reviewed for security.</p><button onClick={()=>setDone(true)} className="h-12 w-full rounded-lg bg-blue font-bold text-white">Continue</button></div></main><MobileNav/></div>}
function Select({label,value}:{label:string;value:string}){return <label className="block text-xs font-bold">{label}<div className="mt-2 flex h-14 items-center rounded-lg border border-line bg-white px-4 text-sm"><span className="flex-1">{value}</span><ChevronDown size={16}/></div></label>}
