"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
import { CirclePlus, Download, FileText, Search, X } from "lucide-react";
import { Sidebar } from "@/components/dashboard/sidebar";
import { MobileNav } from "@/components/dashboard/mobile-nav";
import { AccountsHeader } from "@/components/accounts/accounts-header";
import { invoices, money, type InvoiceStatus } from "./invoice-data";

type Filter="All"|InvoiceStatus;
export function InvoicesPage(){const [filter,setFilter]=useState<Filter>('All');const [query,setQuery]=useState('');const [selected,setSelected]=useState<typeof invoices[number]|null>(null);const rows=useMemo(()=>invoices.filter(i=>(filter==='All'||i.status===filter)&&(i.title+i.company+i.id).toLowerCase().includes(query.toLowerCase())),[filter,query]);return <div className="min-h-screen bg-[#f4f7f7] lg:pl-[210px] lg:bg-white"><Sidebar/><AccountsHeader title="Invoices"/><main className="px-5 pb-24 pt-6 lg:px-8 xl:px-16"><div className="mb-6 lg:hidden"><label className="flex h-11 items-center gap-3 rounded-lg bg-white px-4"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search invoices" className="w-full outline-none"/></label></div><div className="hidden grid-cols-3 gap-5 lg:grid"><Stat title="Total Invoices" amount="$95.650,00" sub="Sent 124 invoices" rate="+10%"/><Stat title="Paid Invoices" amount="$85.320,00" sub="From 112 customers" rate="-2%"/><Stat title="Unpaid Invoices" amount="$10.330,00" sub="From 12 customers" rate="+15%"/></div><div className="mt-6 flex items-center justify-between"><div className="flex rounded-lg border border-line bg-white p-1 lg:bg-[#f2f5f5]">{(['All','Paid','Unpaid','Rejected'] as Filter[]).map(f=><button key={f} onClick={()=>setFilter(f)} className={`rounded-md px-5 py-2 text-[11px] font-bold ${filter===f?'bg-black text-white':''}`}>{f}</button>)}</div><Link href="/invoices/new" className="hidden items-center gap-2 text-xs font-bold lg:flex"><CirclePlus size={16}/>Add new invoice</Link></div><div className="mt-5 hidden grid-cols-[1fr_100px_130px_140px_110px_30px] px-5 text-[11px] font-bold text-muted lg:grid"><span>Name</span><span>Id</span><span>Amount</span><span>Due date</span><span>Status</span></div><div className="mt-3 space-y-2">{rows.map(invoice=><button onClick={()=>setSelected(invoice)} key={invoice.id} className="grid min-h-[90px] w-full grid-cols-[1fr_auto] items-center rounded-lg border-line bg-white px-5 text-left lg:min-h-[66px] lg:grid-cols-[1fr_100px_130px_140px_110px_30px] lg:border"><div className="flex items-start"><FileText size={15} className="mr-4 mt-1 text-muted"/><div><b className="text-xs">{invoice.title}</b><p className="mt-1 hidden text-xs text-muted lg:block">{invoice.company}</p><p className="mt-2 text-xs font-bold lg:hidden">{money(invoice.amount)}</p></div></div><span className="hidden text-xs lg:block">{invoice.id}</span><b className="hidden text-xs lg:block">{money(invoice.amount)}</b><span className="text-xs text-muted lg:text-ink">{invoice.date}</span><Status status={invoice.status}/><span className="hidden lg:block">•••</span></button>)}</div><Link href="/invoices/new" className="fixed bottom-24 right-5 flex h-12 w-12 items-center justify-center rounded-full bg-blue text-white shadow-lg lg:hidden"><CirclePlus/></Link></main><MobileNav/>{selected&&<InvoiceModal invoice={selected} onClose={()=>setSelected(null)}/>}</div>}
function Stat({title,amount,sub,rate}:{title:string;amount:string;sub:string;rate:string}){return <div className="rounded-xl border border-line p-5"><p className="text-sm text-muted">{title}</p><b className="mt-3 block text-xl">{amount}</b><div className="mt-2 flex justify-between text-xs"><span>{sub}</span><b className={rate.startsWith('+')?'text-green-500':'text-pink-500'}>{rate}</b></div></div>}
function Status({status}:{status:InvoiceStatus}){return <span className={`rounded-md px-3 py-2 text-center text-[10px] font-bold ${status==='Paid'?'bg-green-50 text-green-500':status==='Unpaid'?'bg-amber-50 text-amber-500':'bg-pink-100 text-pink-500'}`}>{status}</span>}
function InvoiceModal({invoice,onClose}:{invoice:typeof invoices[number];onClose:()=>void}){return <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/80 lg:items-center" onClick={onClose}><div className="w-full rounded-t-2xl bg-white lg:w-[430px] lg:rounded-xl" onClick={e=>e.stopPropagation()}><div className="h-36 rounded-t-2xl bg-[#eef2f2] p-5"><div className="flex justify-between"><b>{invoice.title}</b><button onClick={onClose}><X size={17}/></button></div></div><div className="px-6 pb-7 text-center"><span className="-mt-10 inline-flex h-16 w-16 items-center justify-center rounded-full border-4 border-white bg-white text-2xl">●</span><h2 className="mt-4 text-xl font-bold">{invoice.company}</h2><p className="mt-1 text-sm text-muted">22 May 2022, 2:15 AM</p><div className="mt-3"><Status status={invoice.status}/></div><div className="mt-6 text-sm">{[["Invoice id",invoice.id],["Send To","Dpt 98, 44-46 Morningside Rd"],["Zip Code","EH10 4BF"],["Email",invoice.email],["Amount",money(invoice.amount)],["Tax 10%",money(invoice.amount/11)]].map(([a,b])=><div key={a} className="flex justify-between border-b border-line py-3"><span>{a}</span><b className="max-w-[65%] text-right">{b}</b></div>)}</div><button onClick={()=>window.print()} className="mt-5 h-12 w-full rounded-lg border border-line text-sm font-bold"><Download className="mr-2 inline" size={15}/>Download PDF</button></div></div></div>}
